### ISSUE TITLE
Pass -Xdemangler to llvm-cov export

### ISSUE THREAD

**Issue by smoelius** [taiki-e/cargo-llvm-cov#325]
Some of my coverage reports indicate very poor function coverage ([example](https://trailofbits.github.io/dylint/coverage/dylint/src/name_toolchain_map/maybe_library.rs.func-sort-c.html)).

However, some of the functions reported to execute 0 times have names quite similar to those of other functions. Example:
```
_RNvMNtNtCsk44e2dZHn18_6dylint18name_toolchain_map13maybe_libraryNtB2_12MaybeLibrary4path
_RNvMNtNtCsdF3WtUSOfWY_6dylint18name_toolchain_map13maybe_libraryNtB2_12MaybeLibrary4path
           ^^^^^^^^^^^
```

If I am interpreting the [Rust name mangling](https://rust-lang.github.io/rfcs/2603-rust-symbol-name-mangling-v0.html) spec correctly, those two identifiers differ in their "crate disambiguator".

My suspicion is that the two functions are really a single function coming from two different builds of a single crate. Does that sound plausible?

If so, is there a way to merge coverage by ignoring crate dismbiguators?

---

I found #50, and I apologize if this is a duplicate. But I think [the code](https://github.com/trailofbits/dylint/blob/42ccc586e6305513386578849eb3d18bab72562c/.github/workflows/coverage.yml#L38-L50) that generated  the above repot already incorporates #50's fix.

**Comment by smoelius** [comment]
I have a [workaround using `sed`](https://github.com/trailofbits/dylint/pull/980/files).

Would you like me to close this?

**Comment by taiki-e** [comment]
Hmm. Ideally, this should be handled on the rustc or LLVM side, but it is probably not easy, so I'm open to providing a workaround on the cargo-llvm-cov side, but I don't feel that 'sed'ing is a robust way.

**Comment by smoelius** [comment]
As mentioned in https://github.com/taiki-e/cargo-llvm-cov/issues/341#issuecomment-1900551556, running `rustfilt` on the lcov file resolved the issue for me.

**Comment by taiki-e** [comment]
As said in https://github.com/taiki-e/cargo-llvm-cov/issues/341#issuecomment-1900629918, this should be fixed by fixing our demangler implementation.

**Comment by taiki-e** [comment]
This probably has been fixed in v0.6.7 (https://github.com/taiki-e/cargo-llvm-cov/pull/354). Could you recheck this with v0.6.7?

**Comment by smoelius** [comment]
@taiki-e Sorry I overlooked your message. I just tried again. From what I can tell, I still need to run `rustfilt` as described in https://github.com/taiki-e/cargo-llvm-cov/issues/341#issuecomment-1900551556.

Just so that we're on the same page, the attached image is what currently I see. Is it what you'd expect?

<img width="1425" alt="Screenshot 2024-07-23 at 2 43 12 PM" src="https://github.com/user-attachments/assets/dbf84c11-1b98-461f-a162-69148ba8498b">

**Comment by taiki-e** [comment]
If lcov (or what you are using) doesn't support demangling of rust symbol, it is expected result, at least with the current implementation. We currently doesn't pass `-Xdemangler` to `llvm-cov export`.
https://github.com/taiki-e/cargo-llvm-cov/blob/4039500dc7ce5874748769166f1f481be294c90f/src/main.rs#L1008-L1046

I think it is fine to pass the `-Xdemangler` to `llvm-cov export`. ...I didn't know it was needed as neither codecov nor coveralls needed it.

**Comment by smoelius** [comment]
I'm not sure if it helps, but here is the [code that generated that report](https://github.com/trailofbits/dylint/blob/45ae0cf94ba056f3d6f9dea3a8f6553fc4b8a0e3/.github/workflows/coverage.yml#L41-L53):
```yaml
      - name: Coverage
        run: |
          for X in . driver utils/linting; do
            pushd "$X"
            cargo llvm-cov --coverage-target-only --target x86_64-unknown-linux-gnu --workspace --exclude dylint_examples --exclude alpine --failure-mode all --lcov --output-path coverage.lcov
            popd
          done

      - name: Install lcov
        run: sudo apt install lcov

      - name: Generate html
        run: find . -name coverage.lcov -print0 | xargs -0 genhtml --output-directory coverage
```
