### ISSUE TITLE
`target.'cfg(all())'.rustflags` not supported (yet)?

### ISSUE THREAD

**Issue by smoelius** [taiki-e/cargo-llvm-cov#332]
I have a [test](https://github.com/trailofbits/dylint/blob/master/cargo-dylint/tests/custom_toolchain.rs) that involves the following [`.cargo/config.toml` file](https://github.com/trailofbits/dylint/blob/master/internal/template/.cargo/config.toml):
```toml
[target.'cfg(all())']
rustflags = ["-C", "linker=dylint-link"]

# For Rust versions 1.74.0 and onward, the following alternative can be used
# (see https://github.com/rust-lang/cargo/pull/12535):
# linker = "dylint-link"
```
The test works fine when run under `cargo test`, but fails when run under `cargo-llvm-cov`.

On the other hand, if you comment out the `rustflags...` line in the above, and uncomment the the `# linker...` line, the test works under `cargo-llvm-cov`.

Is it possible `cargo-llvm-cov` doesn't yet support `target.'cfg(all())'.rustflags`?

The following commands should reproduce the issue:
```
cargo install dylint-link
git clone https://github.com/trailofbits/dylint
cd dylint
cargo test -p cargo-dylint --test custom_toolchain
cargo llvm-cov -p cargo-dylint --test custom_toolchain
```
