### ISSUE TITLE
Github Action workflow not working as expected.

### ISSUE THREAD

**Issue by dominique120** [taiki-e/cargo-llvm-cov#388]
I'm having an issue here with the workflow file. I'm not sure if its an issue with my setup of something wrong with the workflow itself. 

I've set up the action file in this way:
```
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run llvm-cov coverage analysis
        run: cargo llvm-cov --fail-under-functions 70 --fail-under-lines 75
```

These are the results of the pipeline:
![image](https://github.com/user-attachments/assets/671d57a5-98cc-4a68-9cd1-8f92cd1b5643)

**Comment by taiki-e** [comment]
Could you provide more info on the workflow?

It does not appear to be a GitHub-hosted runner and probably GITHUB_PATH does not handled correctly.

**Comment by dominique120** [comment]
They are self hosted. Here is the complete job:
```
  coverage:
    strategy:
      fail-fast: false

    runs-on: [ self-hosted, default ]

    steps:
      - uses: actions/checkout@v2
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run llvm-cov coverage analysis
        run: cargo llvm-cov --fail-under-functions 70 --fail-under-lines 75
```

Worst case scenario I can just install via cargo and use it like that.
